import { BookOpen, LoaderCircle, Search } from "lucide-react";
import { useState } from "react";
import type { FormEvent } from "react";
import { searchRag } from "../api";
import type { RagResult } from "../types";

function Rag() {
  const [form, setForm] = useState({ route: "safety", risk: "끼임", equipment: "컨베이어", location: "제조 1라인", description: "" }); const [result, setResult] = useState<RagResult | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const submit = async (e: FormEvent) => { e.preventDefault(); setLoading(true); setError(""); try { setResult(await searchRag({ route: form.route, top_k: 5, event: { source: "manual", risk_type: form.risk, equipment: form.equipment, location: form.location, description: form.description } })); } catch (err) { setError(err instanceof Error ? err.message : "검색에 실패했습니다."); } finally { setLoading(false); } };
  return <div><div className="page-heading"><div><h1>안전 근거 검색</h1><p className="page-desc">현장 상황과 관련된 산업안전 및 개인정보 근거를 검색합니다.</p></div></div><div className="tool-layout"><form className="panel tool-form" onSubmit={submit}><div className="segmented"><button type="button" className={form.route === "safety" ? "active" : ""} onClick={() => setForm({...form, route:"safety"})}>산업안전</button><button type="button" className={form.route === "privacy" ? "active" : ""} onClick={() => setForm({...form, route:"privacy"})}>개인정보</button></div><div className="field-row"><label>위험 유형<input value={form.risk} onChange={(e) => setForm({...form, risk:e.target.value})}/></label><label>설비<input value={form.equipment} onChange={(e) => setForm({...form, equipment:e.target.value})}/></label></div><label>발생 위치<input value={form.location} onChange={(e) => setForm({...form, location:e.target.value})}/></label><label>상황 설명<textarea rows={7} required value={form.description} onChange={(e) => setForm({...form, description:e.target.value})} placeholder="관찰된 상황을 구체적으로 입력하세요."/></label>{error && <p className="error-text">{error}</p>}<button className="button full" disabled={loading}>{loading ? <><LoaderCircle className="spin"/>검색 중</> : <><Search/>근거 검색</>}</button></form><section className="panel result-panel"><h2>검색 결과</h2>{!result ? <div className="empty-state"><BookOpen/><p>검색 조건을 입력해 주세요.</p></div> : <><div className="query-summary"><small>검색 문장</small><p>{result.query}</p><div>{result.inferred_hazard_tags.map((t) => <span className="tag" key={t}>{t}</span>)}</div></div><div className="evidence-list">{result.results.map((item) => <article key={item.chunk_id}><span className="rank">{item.rank}</span><div><h3>{item.section || item.source_filename || "안전 근거"}</h3><small>{item.source_filename} · {(item.adjusted_score * 100).toFixed(1)}%</small><p>{item.parent_text || item.text}</p></div></article>)}</div></>}</section></div></div>;
}
export default Rag;
